# Generated by Django 3.0.5 on 2024-12-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_question_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='subject',
            new_name='subject_id',
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(max_length=50),
        ),
    ]
