# Generated by Django 5.1.4 on 2024-12-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_alter_course_id_alter_difficulty_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
